// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

// app/javascript/controllers/index.js
import { application } from "./application"
import PongGameController from "./pong_game_controller"

application.register("pong-game", PongGameController)
